### ISSUE TITLE
Dont create a module if the build process fails

### ISSUE THREAD

**Issue by dipietrantonio** [Pawseyops/maali#102]
There is a user that reported

"I've been investigating a bit and it seems that even though I get the error when executing "maali -t openmpi -v 3.1.3" module avail now shows that openmpi/3.1.3 is available and I can load it without error."

**Comment by marcodelapierre** [comment]
As far as I know maali does stop if build fails, provided the cygnet does things right, in particular all commands have to be submitted through the "maali_run" function, that does exit code checking.
I will double check the maali script, and the openmpi cygnet.

**Comment by marcodelapierre** [comment]
cygnet looks fine, using the default maali_build
https://github.com/PawseySC/maali-cygnet/blob/master/sles12sp3/openmpi.cyg

**Comment by marcodelapierre** [comment]
Closing this one, I can confirm that `maali` will stop if a `maali_run` instance fails.
I suspect the case reported by the user is one where multiple installations are performed for the same tool, with no cleaning (`maali -x`) in between, so that dangling files from previous installations may be present.
