### ISSUE TITLE
Option to disable nuking the directories

### ISSUE THREAD

**Issue by skjerven** [Pawseyops/maali#54]
Sometimes when debugging a new build for a complicated package (OpenFOAM and VisIt come to mind) it'd be nice to disable the directory erasing feature.  It's time-wasting to nuke directories every time there's a small error to fix (bash syntax error, compiler flag, etc.), particularly with builds that take hours to compile.

Ideally we could restart the build from where we left off.  The alternative is to build everything outside of Maali while debugging a new build and hope it all works in Maali.

**Comment by dgrimreaper** [comment]
This is only risk-free if you only build for a single compiler/architecture combination, otherwise you might have it die for say gcc/7 but maali then tries to start the rebuild with gcc/4.  (I've had this with c++11 issues).  The way around this is for maali to save its state, but that's a bit messy.

I usually do that sort of debugging outside of maali.  Just let maali run and die, and then in a new terminal load up the appropriate modules and run "make" or whatever.

**Comment by marcodelapierre** [comment]
For a hard-to-build package, I'd advise to develop the build recipe outside maali, and then embed it into a cygnet file once it works (still worth, enables wider reproducibility on Pawsey systems).
The latter migration is normally smooth. The main thing to remind people when outside maali is, when on Crays, to set `export CRAYPE_LINK_TYPE=dynamic`.
